# Generated by Django 5.0.1 on 2024-01-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_remove_videocard_chipset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocard',
            name='effective_memory_frequency',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Эффективная частота памяти'),
        ),
    ]
