# Generated by Django 5.0.1 on 2024-01-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_videocard_effective_memory_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocard',
            name='standard_clock_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Стандартная тактовая частота видеочипа'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='turbo_clock_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Турбо-тактовая частота'),
        ),
    ]
