# Generated by Django 5.0.1 on 2024-01-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_rename_intel_chipset_motherboard_chipset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='chipset',
            field=models.CharField(max_length=50, verbose_name='Чипсет'),
        ),
    ]
