# Generated by Django 5.0.1 on 2024-01-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_alter_motherboard_chipset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='num_usb_back_panel',
            field=models.CharField(max_length=200, verbose_name='Количество и тип USB на задней панели'),
        ),
    ]
