# Generated by Django 5.0.1 on 2024-01-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_motherboard_num_usb_back_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='toslink_spdif_optical',
        ),
    ]
